### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by jpzs444** [kmryashasvi/patterns#26]
Good day! I would like to share some suggestions to improve your README file:

- [x] Add a title. (ex. Patterns)
- [x] Add a short description about the repository (below the title).
- [x] Add a section for the objective(s).
- [x] Add a section indicating the rules on how to provide the solutions and how to contribute to the repository. This will make the repository organized.

Also, after you're done and satisfied with your README file, I can edit some grammatical errors if there are any. Thank you for your time!

**Comment by kmryashasvi** [comment]
Do whatever you can to improve this repo,
and so will I.
Thanks
